fix(case): punish failing trials with large objective values

diff --git a/SandiaD_LTS/Allrun b/SandiaD_LTS/Allrun
--- a/SandiaD_LTS/Allrun
+++ b/SandiaD_LTS/Allrun
@@ -29,12 +29,26 @@ foamDictionary system/controlDict -entry endTime -set 1500
 foamDictionary constant/chemistryProperties -entry chemistry -set off
 #foamDictionary -entry refineInterval -set "$refineInterval" constant/dynamicMeshDict
 runApplication decomposePar
+set +e
 runParallel $(getApplication)
+if [ $? -ne 0 ]; then
+    echo "Solver $(getApplication) failed, objectives will be punished for this trial"
+    touch FAILED
+    exit 0
+fi
+set -e
 
 # Run with chemistry until flame reaches its full size
 foamDictionary system/controlDict -entry writeInterval -set 100
 foamDictionary system/controlDict -entry endTime -set 5000
 foamDictionary constant/chemistryProperties -entry chemistry -set on
+set +e
 runParallel -a $(getApplication)
+if [ $? -ne 0 ]; then
+    echo "Solver $(getApplication) failed, objectives will be punished for this trial"
+    touch FAILED
+    exit 0
+fi
+set -e
 
 #------------------------------------------------------------------------------
